<?php

namespace QT\SystemeBundle\Repository;

/**
 * NoeudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoeudRepository extends \Doctrine\ORM\EntityRepository
{
}
