qt_deploiement:
    resource: "@QTDeploiementBundle/Resources/config/routing.yml"
    prefix:   /

qt_systeme:
    resource: "@QTSystemeBundle/Resources/config/routing.yml"
    prefix:   /

qt_cartographie:
    resource: "@QTCartographieBundle/Resources/config/routing.yml"
    prefix:   /

qt_documents:
    resource: "@QTDocumentsBundle/Resources/config/routing.yml"
    prefix:   /

qt_appli:
    resource: "@QTAppliBundle/Resources/config/routing.yml"
    prefix:   /

qt_admin:
    resource: "@QTAdminBundle/Resources/config/routing.yml"
    prefix:   /

qt_blocnotes:
    resource: "@QTBlocnotesBundle/Resources/config/routing.yml"
    prefix:   /

# QT essai FOSUserBundle

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile