qt_documents:
    resource: "@QTDocumentsBundle/Resources/config/routing.yml"
    prefix:   /

qt_systeme:
    resource: "@QTSystemeBundle/Resources/config/routing.yml"
    prefix:   /

qt_appli:
    resource: "@QTAppliBundle/Resources/config/routing.yml"
    prefix:   /

qt_admin:
    resource: "@QTAdminBundle/Resources/config/routing.yml"
    prefix:   /

qt_blocnotes:
    resource: "@QTBlocnotesBundle/Resources/config/routing.yml"
    prefix:   /

