# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security: 
    providers:
        db_provider:
            entity:
                class: QT\AdminBundle\Entity\Utilisateur
                property: username
        #in_memory:
            #memory:
                #users:
                    #user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    #admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        QT\AdminBundle\Entity\Utilisateur:
            algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            http_basic: ~

            pattern:  ^/
            provider: db_provider
            
            logout:
                path:   /logout
                target: /
            
    access_control:
        - { path: ^/utilisateurs, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
        
    role_hierarchy:
        # Un admin hérite des droits d'auteur et de modérateur
        #ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
