accueil_cartographie:
    path:     /cartographie
    defaults: { _controller: QTCartographieBundle:Cartographie:index }

afficher_applicatif:
    path:     /applicatif
    defaults: { _controller: QTCartographieBundle:Applicatif:index }
    
afficher_plateforme:
    path:     /plateforme
    defaults: { _controller: QTCartographieBundle:Plateforme:index }

creer_hyperviseur:
    path: hyperviseur/edit
    defaults: {_controller: QTCartographieBundle:Hyperviseur:editerHyperviseur}


editer_hyperviseur:
    path: hyperviseur/edit/{hyperviseur_num}
    defaults: {_controller: QTCartographieBundle:Hyperviseur:editerHyperviseur}
    requirements:
        hyperviseur_num: \d+