afficher_applicatif:
    path:     /carto_applicatif
    defaults: { _controller: QTCartographieBundle:Applicatif:index }
       
creer_bundle:
    path: /bundle/edit
    defaults: {_controller: QTCartographieBundle:Applicatif:editerBundle}
    
editer_bundle:
    path: /bundle/edit/{bundle_num}
    defaults: {_controller: QTCartographieBundle:Applicatif:editerBundle}
    requirements:
        bundle_num: \d+
        
        
   
afficher_mutualisation:
    path:     /mutualisation
    defaults: { _controller: QTCartographieBundle:Mutualisation:index }
 
 
    
afficher_cartographie_systeme:
    path:     /carto_systeme
    defaults: { _controller: QTCartographieBundle:Mutualisation:afficherCartographieSysteme }

afficher_hyperviseur:
    path: /hyperviseur/{hyperviseur_num}
    defaults: {_controller: QTCartographieBundle:Hyperviseur:afficherHyperviseur}
    requirements:
        hyperviseur_num: \d+

creer_hyperviseur:
    path: /hyperviseur/edit
    defaults: {_controller: QTCartographieBundle:Hyperviseur:editerHyperviseur}

editer_hyperviseur:
    path: /hyperviseur/edit/{hyperviseur_num}
    defaults: {_controller: QTCartographieBundle:Hyperviseur:editerHyperviseur}
    requirements:
        hyperviseur_num: \d+




afficher_application:
    path:     /application/{application_num}
    defaults: { _controller: QTCartographieBundle:Application:afficherApplication }
    requirements:
        application_num: \d+

creer_application:
    path:     /application/edit/
    defaults: { _controller: QTCartographieBundle:Application:editerApplication }

editer_application:
    path:     /application/edit/{application_num}
    defaults: { _controller: QTCartographieBundle:Application:editerApplication }
    requirements:
        application_num: \d+




afficher_noeud:
    path: /application/{application_num}/noeud/{noeud_num}
    defaults: {_controller: QTCartographieBundle:Systeme:afficherNoeud}
    requirements:
        noeud_num: \d+
        application_num: \d+
    
creer_noeud:
    path: /application/{application_num}/noeud/edit/
    defaults: {_controller: QTCartographieBundle:Systeme:editerNoeud}
    requirements:
        application_num: \d+
        
editer_noeud:
    path: /application/{application_num}/noeud/edit/{noeud_num}
    defaults: {_controller: QTCartographieBundle:Systeme:editerNoeud}
    requirements:
        noeud_num: \d+
        application_num: \d+
 
supprimer_noeud:
    path: /systeme/suppr/{noeud_num}
    defaults: {_controller: QTCartographieBundle:Systeme:supprimerNoeud}
    requirements:
        noeud_num: \d+
   
  
  
        
afficher_carto_donnee:
    path:     /carto_donnee
    defaults: { _controller: QTCartographieBundle:Donnee:index }
 