creer_topic:
    path:   /topic/edit/{topic_type}
    defaults: {_controller: QTBlocnotesBundle:Topic:editerTopic}
    
editer_topic:
    path:   /topic/edit/{topic_type}/{topic_num}
    defaults: {_controller: QTBlocnotesBundle:Topic:editerTopic}
    requirements:
        num_topic: \d

supprimer_topic:
    path:   /topic/suppr/{topic_num}
    defaults: {_controller: QTBlocnotesBundle:Topic:supprimerTopic}
    requirements:
        num_topic: \d
        
lister_topic:
    path:   /topics
    defaults: {_controller: QTBlocnotesBundle:TopicListe:listerTopic}
    
supprimer_topic_pj:
    path:   /topic/pj/suppr/{pj_num}
    defaults: {_controller: QTBlocnotesBundle:Topic:supprimerPj}
    requirements:
        pj_num: \d+
 
 
 
 
 
creer_bug:
    path:   /bugzilla/edit
    defaults: {_controller: QTBlocnotesBundle:Bugzilla:editerBug}
    
editer_bug:
    path:   /bugzilla/edit/{bug_num}
    defaults: {_controller: QTBlocnotesBundle:Bugzilla:editerBug}
    requirements:
        bug_num: \d+

supprimer_bug:
    path:   /bugzilla/suppr/{bug_num}
    defaults: {_controller: QTBlocnotesBundle:Bugzilla:supprimerBug}
    requirements:
        bug_num: \d+
        
lister_bug:
    path:   /bugzilla
    defaults: {_controller: QTBlocnotesBundle:Bugzilla:listerBug}       