qt_blocnotes_accueil:
    path:     /
    defaults: { _controller: QTBlocnotesBundle:Accueil:listerTopic }

qt_blocnotes_utilisateur:
    path:   /user/{userName}
    defaults: {_controller: QTBlocnotesBundle:User:index}