accueil:
    path:     /
    defaults: { _controller: QTBlocnotesBundle:Accueil:listerTopic }

utilisateur:
    path:   /utilisateur/{userName}
    defaults: {_controller: QTBlocnotesBundle:Utilisateur:index}
    
topic_edition:
    path:   /topic/edit/{num_topic}
    defaults: {_controller: QTBlocnotesBundle:Topic:editerTopic}

utilisateurs:
    path:   /utilisateurs
    defaults: {_controller: QTBlocnotesBundle:Utilisateurs:index}
