accueil:
    path:     /
    defaults: { _controller: QTBlocnotesBundle:Accueil:listerTopic }

utilisateur:
    path:   /user/{userName}
    defaults: {_controller: QTBlocnotesBundle:User:index}
    
topic_edition:
    path:   /topic/edit/{num_topic}
    defaults: {_controller: QTBlocnotesBundle:Topic:editerTopic}
