<?php

namespace QT\CartographieBundle\Repository;

/**
 * BundleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BundleRepository extends \Doctrine\ORM\EntityRepository
{
}
