afficher_metrologie:
    path: metrologie
    defaults: {_controller: QTSystemeBundle:Metrologie:index}

afficher_metrologie_hyperviseur:
    path: /metrologie/profiling/{hyperviseur_num}
    defaults: {_controller: QTSystemeBundle:Metrologie:afficherProfiling}
    requirements:
        hyperviseur_num: \d+
  
afficher_profiling:
    path: /metrologie/profiling/{hyperviseur_num}/{profiling_type}
    defaults: {_controller: QTSystemeBundle:Metrologie:afficherProfiling}
    requirements:
        hyperviseur_num: \d+