afficher_metrologie:
    path: metrologie
    defaults: {_controller: QTSystemeBundle:Metrologie:index}
    
afficher_systeme:
    path: systeme
    defaults: {_controller: QTSystemeBundle:Systeme:listerNoeud}
    
creer_noeud:
    path: systeme/edit/
    defaults: {_controller: QTSystemeBundle:Systeme:editerNoeud}
        
editer_noeud:
    path: systeme/edit/{noeud_num}
    defaults: {_controller: QTSystemeBundle:Systeme:editerNoeud}
    requirements:
        noeud_num: \d
 
afficher_application:
    path: application
    defaults: {_controller: QTSystemeBundle:Application:afficherApplication} 
   
editer_application:
    path: application/edit/
    defaults: {_controller: QTSystemeBundle:Application:editerApplication}
    
supprimer_noeud:
    path: systeme/suppr/{noeud_num}
    defaults: {_controller: QTSystemeBundle:Systeme:supprimerNoeud}
    requirements:
        noeud_num: \d