accueil:
    path:     /
    defaults: { _controller: QTAppliBundle:Accueil:index }

utilisateur:
    path:   /utilisateur/{userName}
    defaults: {_controller: QTBlocnotesBundle:Utilisateur:index}

creer_topic:
    path:   /topic/edit
    defaults: {_controller: QTBlocnotesBundle:Topic:editerTopic}
    
topic_edition:
    path:   /topic/edit/{num_topic}
    defaults: {_controller: QTBlocnotesBundle:Topic:editerTopic}
    requirements:
        num_topic: \d

utilisateurs:
    path:   /utilisateurs
    defaults: {_controller: QTAdminBundle:Utilisateurs:index}

ajouter_domaine:
    path:   /domaine
    defaults: {_controller: QTAdminBundle:Domaine:index}
    
lister_topic:
    path:   /topics
    defaults: {_controller: QTBlocnotesBundle:TopicListe:listerTopic}