<?php

namespace QT\BlocnotesBundle\Repository;

/**
 * BugzillaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BugzillaRepository extends \Doctrine\ORM\EntityRepository
{
}
