<?php

namespace QT\BlocnotesBundle\Repository;

/**
 * DomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineRepository extends \Doctrine\ORM\EntityRepository
{
}
