<?php

namespace QT\BlocnotesBundle\Repository;

/**
 * VerrouRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerrouRepository extends \Doctrine\ORM\EntityRepository
{
}
