creer_utilisateur:
    path:   /utilisateurs
    defaults: {_controller: QTAdminBundle:Utilisateurs:index}
    
editer_utilisateur:
    path:   /utilisateurs/{utilisateur_num}
    defaults: {_controller: QTAdminBundle:Utilisateurs:index}
    
supprimer_utilisateur:
    path:   /utilisateurs/suppr/{utilisateur_num}
    defaults: {_controller: QTAdminBundle:Utilisateurs:supprimerUtilisateur}

ajouter_domaine:
    path:   /domaine
    defaults: {_controller: QTAdminBundle:Domaine:index}
    
afficher_profil:
    path: profil
    defaults: {_controller: QTAdminBundle:Profil:index}