creer_utilisateurs:
    path:   /utilisateurs
    defaults: {_controller: QTAdminBundle:Utilisateurs:index}
    
editer_utilisateurs:
    path:   /utilisateurs/{utilisateur_num}
    defaults: {_controller: QTAdminBundle:Utilisateurs:index}

ajouter_domaine:
    path:   /domaine
    defaults: {_controller: QTAdminBundle:Domaine:index}
    
afficher_profil:
    path: profil
    defaults: {_controller: QTAdminBundle:Profil:index}